# CONFIGURACOES GERAIS
PRINT = False
CONEX = "OFFLINE" #MUST BE: OFFLINE, ETHERNET OR SERIAL
DELAY = False

##KEYS
UP_LEFT_KEY = 113
UP_KEY = 119
UP_RIGHT_KEY = 101
LEFT_KEY = 97
STOP_KEY = 115 
RIGHT_KEY = 100
DOWN_LEFT_KEY = 122
DOWN_KEY = 120 
DOWN_RIGHT_KEY = 99
PLUS_LIGHT_KEY = 111
MINUS_LIGHT_KEY = 112

##### PROTOCOLO (HEADCHAR, ENDCHAR)
HEADCHAR = b'\xfd'
ENDCHAR = b'\xfe'
BYTES_IN_MSG = 3
BYTES_IN_RESP = 8
#INFOCYCLE = [b'\x10', b'\x11', b'\x12', b'\x13', b'\x14', b'\x15']
ANYINFO = b'\x30'

#NETWORK
###ETHERNET: (IP, PORT)
######ARDUINO:
IP = "192.168.0.120"
PORT = 23

#SERIAL:
COM_PORT = "com3"
